version: '2'

services:
  react:
    image: node:8
    environment:
      - REACT_APP_API_URL= http://localhost:8008/dev/
    command: ["tail", "-f", "/dev/null"]
    ports:
      - '3004:3000'
    volumes:
        - .:/usr/src/app
    working_dir: /usr/src/app
    container_name: createreactapp-circleci-gcp
