defaults: &build
  working_directory: ~/alejandronunez/createreactapp-circleci-gcp
  parallelism: 1
  shell: /bin/bash --login
  docker:
  - image: circleci/node:8

version: 2

jobs:
  dependencies:
    <<: *build
    steps:
    - checkout
    - attach_workspace:
        at: /

    # Restore cache
    - restore_cache:
        keys:
          - npm-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

    # Installing pip requirements
    - run: yarn install

    # Save cache
    - save_cache:
        key: npm-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
        paths:
        - node_modules

    - persist_to_workspace:
        root: /
        paths:
          - home/circleci/alejandronunez/createreactapp-circleci-gcp/node_modules

  unit_test:
    <<: *build
    steps:
    - checkout
    - attach_workspace:
        at: /

    # Unit Test
    - run: yarn test

  integration_test:
    <<: *build
    steps:
    - checkout
    - attach_workspace:
        at: /

    # Integration Test
    - run: yarn test

  feature_test:
    <<: *build
    steps:
    - checkout
    - attach_workspace:
        at: /

    # Feature Test
    - run: yarn test


  eslint:
    <<: *build
    steps:
    - checkout
    - attach_workspace:
        at: /

    # Run Eslint
    - run: yarn lint:check

  generate_production:
    <<: *build
    steps:
    - checkout
    - attach_workspace:
        at: /

    # Run generation of production files
    - run: yarn build

    - store_artifacts:
        path: build

    # Saving build files to deploy
    - persist_to_workspace:
        root: /
        paths:
          - home/circleci/alejandronunez/createreactapp-circleci-gcp/build

  deploy:
    <<: *build
    docker:
      - image: google/cloud-sdk
        environment:
          GAE_SDK_PATH: /usr/lib/google-cloud-sdk
    steps:
    - checkout
    - attach_workspace:
        at: /

    # Start deploy
    - run: apt-get update
    - run: apt-get install -y fabric
    - run: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > $HOME/gcloud-service-key.json

    # Deploy script
    - run: fab -f ./deploy.py deploy


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - dependencies
      - unit_test:
          requires:
            - dependencies
      - integration_test:
          requires:
            - dependencies
      - feature_test:
          requires:
            - dependencies
      - eslint:
          requires:
            - unit_test
            - integration_test
            - feature_test
      - generate_production:
          requires:
          - unit_test
          - integration_test
          - feature_test
      - deploy:
          requires:
            - generate_production
